Remove the container and helm chart hacks
uyuni-project/uyuni-releng-tools pull request #9
Opened 2024-01-18 21:40 UTC by cbosdo

Delegate the build-specific parts to tito and the push parts to a new plugin script called `push.sh` that could be in the package sources.

2024-01-19 17:38 UTC, deneb-alpha requested changes
Sorry, I would add  a changelog  entry for this big change

2024-01-22 09:27 UTC, cbosdo commented
> Sorry, I would add a changelog entry for this big change

Added

2024-01-22 09:42 UTC, deneb-alpha approved these changes
LGTM, thanks

2024-01-22 09:50 UTC, raulillo82 approved these changes

2024-01-22 10:43 UTC, merged